apiVersion: v1
kind: Service
metadata:
  name: energy-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: energy-consumption-prediction
  ports:
    - port: 80 
      targetPort: 9696